/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as FindsSlugRouteImport } from './routes/finds.$slug'
import { Route as PeoplesSlugRouteImport } from './routes/peoples.$slug'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as VoicesSlugRouteImport } from './routes/voices.$slug'
import { Route as WorldsSlugRouteImport } from './routes/worlds.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const FindsSlugRoute = FindsSlugRouteImport.update({
  id: '/finds/$slug',
  path: '/finds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplesSlugRoute = PeoplesSlugRouteImport.update({
  id: '/peoples/$slug',
  path: '/peoples/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesSlugRoute = VoicesSlugRouteImport.update({
  id: '/voices/$slug',
  path: '/voices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugRoute = WorldsSlugRouteImport.update({
  id: '/worlds/$slug',
  path: '/worlds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/finds/$slug': typeof FindsSlugRoute
  '/peoples/$slug': typeof PeoplesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/voices/$slug': typeof VoicesSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/finds/$slug': typeof FindsSlugRoute
  '/peoples/$slug': typeof PeoplesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/voices/$slug': typeof VoicesSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/finds/$slug': typeof FindsSlugRoute
  '/peoples/$slug': typeof PeoplesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/voices/$slug': typeof VoicesSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codex'
    | '/finds/$slug'
    | '/peoples/$slug'
    | '/places/$slug'
    | '/voices/$slug'
    | '/worlds/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codex'
    | '/finds/$slug'
    | '/peoples/$slug'
    | '/places/$slug'
    | '/voices/$slug'
    | '/worlds/$slug'
  id:
    | '__root__'
    | '/'
    | '/codex'
    | '/finds/$slug'
    | '/peoples/$slug'
    | '/places/$slug'
    | '/voices/$slug'
    | '/worlds/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodexRoute: typeof CodexRoute
  FindsSlugRoute: typeof FindsSlugRoute
  PeoplesSlugRoute: typeof PeoplesSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  VoicesSlugRoute: typeof VoicesSlugRoute
  WorldsSlugRoute: typeof WorldsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finds/$slug': {
      id: '/finds/$slug'
      path: '/finds/$slug'
      fullPath: '/finds/$slug'
      preLoaderRoute: typeof FindsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peoples/$slug': {
      id: '/peoples/$slug'
      path: '/peoples/$slug'
      fullPath: '/peoples/$slug'
      preLoaderRoute: typeof PeoplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices/$slug': {
      id: '/voices/$slug'
      path: '/voices/$slug'
      fullPath: '/voices/$slug'
      preLoaderRoute: typeof VoicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug': {
      id: '/worlds/$slug'
      path: '/worlds/$slug'
      fullPath: '/worlds/$slug'
      preLoaderRoute: typeof WorldsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodexRoute: CodexRoute,
  FindsSlugRoute: FindsSlugRoute,
  PeoplesSlugRoute: PeoplesSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  VoicesSlugRoute: VoicesSlugRoute,
  WorldsSlugRoute: WorldsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
